### PR TITLE
Added method isCurrentPath (twig: is_current_path)

### PR DESCRIPTION
**Pull request by im-bart**
Usage:

```
is_current_path('path name')
```

Returns bool. Name is the same as for `path_for`.

### CODE REVIEW

**Comment by akrabat** [comment]
Thanks. Looks like a useful addition.

**Comment by claviska** [comment]
Would love to see a 2.2 release with this method soon. 👍

**Comment by ivandokov** [comment]
It will be good to add it to the README

**Comment by xandros15** [comment]
$uri is a basepath, not current

**Pull request merged**
