### PR TITLE
Avoiding suspect PHPUnit version

### PR DESCRIPTION
**Pull request by Sam-Burns**

### CODE REVIEW

**Comment by Sam-Burns** [comment]
Will follow up with `phpunit/phpunit` in more detail, but in the meantime I suggest avoiding version `5.7.6`.

**Comment by Sam-Burns** [comment]
Ref: https://github.com/sebastianbergmann/phpunit/issues/2432

**Comment by akrabat** [comment]
So we're calling the wrong phpunit executable?

**Comment by akrabat** [comment]
i.e. should we change travis.yml:

from:

    script: phpunit --coverage-text --configuration phpunit.xml.dist

to

    script: vendor/bin/phpunit --coverage-text --configuration phpunit.xml.dist

**Comment by akrabat** [comment]
See https://github.com/slimphp/Twig-View/pull/73

Thoughts?

**Comment by Sam-Burns** [comment]
Closing in favour of #23

**Pull request closed without merging**
