### PR TITLE
Remove script name if exist when display CSS

### PR DESCRIPTION
**Pull request by chanhong**

### CODE REVIEW

**Comment by geggleto** [comment]
Sorry. I have to :-1: this. I have applications that require the "something".php to be in them.
This option needs to be optional.

**Comment by geggleto** [comment]
Also please see #44

**Comment by chanhong** [comment]
oh, really, but this is only for TwigExtension.
Are you using TwigExtension?

**Comment by geggleto** [comment]
Yup.

**Comment by chanhong** [comment]
how would you solve the css not displaying when the script name is in the url?

**Comment by geggleto** [comment]
Please see #44  As I mentioned above.
https://github.com/slimphp/Twig-View/pull/44/files

**Comment by chanhong** [comment]
It is ok.  I figure out how to make it works using dependencies.php

**Pull request closed without merging**
