### PR TITLE
Add items array to collection

### PR DESCRIPTION
**Pull request by 1f7**

### CODE REVIEW

**Comment by 1f7** [comment]
now add items array possible in `fetch` or `render` methods.
and if used many items `offsetSet` not always convenient.

`offsetAdd` method permit add items array at once.

**Comment by akrabat** [comment]
I like the idea, but aren't sure about the name of `offsetAdd`. The `offsetXxx` methods are commonly expected to be part of the PHP interface and this one isn't.

@silentworks: what are your thoughts?

**Comment by 1f7** [comment]
I agree with you.
candidates: offsetSetArry, offsetSetArray, offsetSetLot, offsetSetMany ...

**Comment by namaless** [comment]
Don't like `set` or following Twig `addGlobal`? I think is much better then this (imho) and following the Twig function name.

**Pull request closed without merging**
