### PR TITLE
Upgrading to Twig 2

### PR DESCRIPTION
**Pull request by Sam-Burns**

### CODE REVIEW

**Comment by akrabat** [comment]
Slim is a PHP 5.5+ framework. If Twig 2 is PHP 7+ only, then we can't take it until Slim becomes PHP 7+ only.

**Comment by ivandokov** [comment]
I'm sorry for the offtopic, but @akrabat brings up an interesting topic. php 5.5 is not receiving even security updates anymore http://php.net/supported-versions.php
Isn't it time to make the framework 5.6+?

**Comment by akrabat** [comment]
While we don't recommend anyone use PHP 5.5 in production, I'm not sure that we want to prevent a live Slim 3 application getting bug fixes because we have arbitrarily changed composer.json. Thoughts @codeguy, @silentworks?

**Comment by ivandokov** [comment]
I doubt there will be cases with websites using 5.5 and still updating the composer packages. These projects are probably not maintained anymore. 
Most if not all developers prefer to update to 5.6 at least unless there is a really weird blocking point.

**Comment by akrabat** [comment]
> I doubt there will be cases with websites using 5.5 and still updating the composer packages. 

Except anyone deploying to Ubuntu 14.04 of course… Which has PHP 5.5 and is supported until May 2019.

**Comment by silentworks** [comment]
I don't think we should set the requirements for PHP 7 until we are releasing a new major version of Slim. So this might be something to consider for Slim 4.

**Comment by Sam-Burns** [comment]
Well do you think there is room for a separate Twig2 branch or a separate extension repo then?  Seems like a shame to stop all users from using Twig2 because it doesn't work with PHP5.5.

**Comment by spekkionu** [comment]
Would changing the requirement in the composer.json to something like `"twig/twig": "1.*|2.*",` work?
This would cause people running php 7+ to get Twig 2 and people still running php 5.x to get Twig 1.x.

Possible issue is that upgrading php could then break applications that are using deprecated Twig features that were removed in 2.0.  Adding twig to the composer.json to lock it to a 1.x release would fix the issue though.

**Comment by Sam-Burns** [comment]
@spekkionu sounds like a genius idea to me.  @akrabat @ivandokov @silentworks anybody else have any thoughts?

**Comment by akrabat** [comment]
Sounds good to me.

I assume we don't use anything that's gone in Twig 2?

We'll need to ensure that the README documents this.

**Comment by spekkionu** [comment]
This might be worth a major version bump as it does have the potential to break an application if they are using Twig 1.x only features and run composer update on php 7+.

**Comment by Sam-Burns** [comment]
@spekkionu I'm not too concerned about that, as I think it's reasonable to expect a user of Twig `1.x` to put something like `"twig/twig": "^1.30"` in their `composer.json` file.  It's worth remembering as well that Twig 2 just removes stuff that was already marked as deprecated in latter versions of Twig 1.

Ultimately though, I guess versioning is up to the project maintainers, and bumping the major version probably wouldn't do any harm.  Just see how they decide to tag it I guess.

**Comment by sylfel** [comment]
Seems to be a good evolution !

**Comment by railto** [comment]
Just throwing in my €0.02, but agree that this should not be done in slim 3, changing the PHP version requirement is one heck of a BC that should only ever be done in a major version upgrade.

**Comment by Sam-Burns** [comment]
@railto This pull request does not change the PHP versions supported - the build is still passing in PHP 5.5.  See https://github.com/Sam-Burns/Twig-View/blob/2522ed02325ffcfc49602676d35ad2585dcacfe1/.travis.yml .

**Comment by akrabat** [comment]
https://travis-ci.org/slimphp/Twig-View/jobs/195254174 failed .

@Sam-Burns can you fix?

**Comment by Sam-Burns** [comment]
@akrabat Please see https://github.com/slimphp/Twig-View/pull/72 .

**Pull request merged**
