### PR TITLE
Create a separate extension for helper functions

### PR DESCRIPTION
**Pull request by akrabat**
Also add `base_url` Twig function.

### CODE REVIEW

**Comment by silentworks** [comment]
The method name seem to communicate one thing while doing something else IMO. I would actually prefer to register the extension manually and doing it externally.

**Comment by akrabat** [comment]
You mean `registerExtension` ? 

I kept that so that the set up of the extension remains:

```php
$container->register(new \Slim\Views\Twig('path/to/templates', [
    'cache' => 'path/to/cache'
]));
```

which is nice and simple to use. I'm not wedded to it though and am happy enough to remove the method and change the README.

**Comment by silentworks** [comment]
if thats the case its probably better to make that method `private`, Having it as `public` confuses me. Although saying that, I still think most users are happy to register it themselves as this is how Slim-Views currently works plus it is easier to override `path_for` and `base_url` with my own extension.

**Comment by akrabat** [comment]
Rebased, removed `registerExtension` and updated README.

**Comment by silentworks** [comment]
The README doesn't look correct to me.

**Comment by akrabat** [comment]
Try now!

**Pull request merged**
