### PR TITLE
Removed use of echo from render method

### LINKED ISSUE #3: Remove `echo` from the render method
Users should be discouraged from using `echo` in their application, and we shouldn't use `echo` in the `render` method ourselves.

For me, the purpose of a PSR-7 based app should be the building of a valid response object during the application phase, and then sending that response at the end. I believe that if you are working with PSR-7 you shouldn't ever be writing to the output directly.

My proposal is to change the `render` method to the following:

```
 public function render(Response $response $template, $data = [])
{
    return  $response->write($this->fetch($template, $data));
}
```

### PR DESCRIPTION
**Pull request by GeeH**
Closes #3

### CODE REVIEW

**Comment by GeeH** [comment]
The only reason it depends on Slim\Http\Response is that I set an expectation that `write` is being called which is part of the Slim implementation rather than the PSR-7 interface specification. Not sure it should depend on an interface that doesn't specify the method we are using in the stub.

**Comment by codeguy** [comment]
Depend on the PSR-7 interface and make changes accordingly.

**Comment by codeguy** [comment]
`$res->getBody()->write(...)`

**Comment by GeeH** [comment]
Roger that.

**Pull request merged**
