### PR TITLE
Fix signature

### PR DESCRIPTION
**Pull request by adriansuter**
Signature should match the interface method signature.

### CODE REVIEW

**Review by l0gicgate — APPROVED** [review]

**Comment by l0gicgate** [comment]
This fails on PHP 7.1:

```text
Fatal error: Declaration of Slim\Views\TwigRuntimeLoader::load(string $class) must be compatible with Twig\RuntimeLoader\RuntimeLoaderInterface::load($class) in /home/travis/build/slimphp/Twig-View/src/TwigRuntimeLoader.php on line 16
```

**Comment by adriansuter** [comment]
Seems that twig is in version 2.12.5 in php 7.1 environment, but 3.0.3 in php 7.2 and up. How do we handle this?

**Comment by l0gicgate** [comment]
I'm guessing they changed minimum php version to 7.2 in anything above 2.12.5 since 7.1 is EOL. We could bump up min version to 7.2 for next release and remove it from the CI

**Comment by adriansuter** [comment]
Yes.

**Comment by l0gicgate** [comment]
@adriansuter are you going to remove PHP 7.1 from CI?

**Comment by adriansuter** [comment]
I have removed Twig 2 support as well. Not sure, if that might be a breaking change.

**Comment by l0gicgate** [comment]
@adriansuter I think this is always a gray area when a PHP version is deprecated. Yes, this is a breaking change since you can't use it with Twig 2 anymore, but composer also won't update if you're running PHP 7.1. Either way, you can still version lock to 3.0.0, only security fixes should be issued via 3.0.x and this will be released as 3.1.x.

**Pull request merged**
