### PR TITLE
Readme file modified for making a small note for avoiding issue #77.

### PR DESCRIPTION
**Pull request by shahariaazam**
https://github.com/slimphp/Twig-View/issues/77

### CODE REVIEW

**Comment by tflight** [comment]
Shouldn't composer take care of that and install the version applicable to the PHP version you are running? (I'm asking because I'm curious.) In issue #77 it would appear the compatibility issue was because your local environment and the environment you deployed to was not running the same version of PHP.

If you are deploying to a lower version of PHP, would it not be better to add your PHP platform version to your composer.json so that it matched your target deployment version? (Again, I'm not saying that is correct, I'm curious. Something like this?

```
    "config": {
        "platform": {
            "php": "5.5.9"
        }
    },
```

I think composer would then recognize which version of Twig is compatible with your target environment.

**Comment by shahariaazam** [comment]
@tflight thanks for your suggestions. Yes, that may do but honestly I didn't check that yet.

I figured this out by keeping main Twig library in composer. I just want to make people conscious about what might happen because I faced that. People should get instructions for any possible confusion in the docs like **README**. So they can be aware of that.

**Comment by silentworks** [comment]
I think we should have had a major version change for this. We should have created a new version that supports Twig 2 and keep the older version to support Twig 1.

**Comment by akrabat** [comment]
I would prefer to see the `platform` setting documented in the README.

**Pull request closed without merging**
