### PR TITLE
Dependency Inject LoaderInterface on Twig Constructor

### LINKED ISSUE #125: 3.x - Twig Constructor Dependency Injection
Currently, the `\Slim\Views\Twig` constructor instantiates a `\Twig\Loader\FilesystemLoader` (in the `createLoader`-method) and a `\Twig\Environment`.

https://github.com/slimphp/Twig-View/blob/89827f4919f5e803abb5e2f40205f8429ea63108/src/Twig.php#L62-L66

Should we add the possibility to pass them to the constructor, such that a user could create those two instances before and outside of the Twig constructor?

Or do we want to prevent users to bring their own instances? So whenever they need something like this, then they have to extend `Twig` and develop their own implementations.

### PR DESCRIPTION
**Pull request by bangzek**
- Change Twig constructor to supply LoaderInterface instead path
- Add Twig::create() that handles the previous constructor functionality

Close #125

### CODE REVIEW

**Comment by adriansuter** [comment]
Should we instantiate the `Environment` in the create method too? So that the constructor does not instantiate anything. That way, everything is decoupled.

**Comment by l0gicgate** [comment]
@adriansuter I'm fine with either or.. I think it's probably better to leave the instantiation in there.. one less thing to do for the user. To the contrary though there's different types of loaders so using the interface is a better idea in this case.

**Comment by bangzek** [comment]
Well there's only one `Environment` but multiple `Loader`, so DI-ing `Environment` doesn't gives us anything.

**Comment by adriansuter** [comment]
Fine, if someone needs a custom environment, then extending Twig is always an option.

**Comment by adriansuter** [comment]
Fine, if someone needs a custom environment, then extending Twig is always an option.

**Pull request merged**
