### PR TITLE
Fix if php in url

### PR DESCRIPTION
**Pull request by chanhong**
This fix is a more generic version from the previous pull request.

### CODE REVIEW

**Comment by akrabat** [comment]
I still think that the solution is to use middleware…

**Comment by chanhong** [comment]
I am unclear with what you mean by "use middleware"
Can you clarify?
Thanks

**Comment by akrabat** [comment]
Something along the lines of:

```php
$app->add(function ($request, $response, $next) {
    $uri = $request->getUri();
    $basePath = rtrim(str_ireplace('index.php', '', $uri->getBasePath()), '/');
    $request = $request->withUri($uri->withBasePath($basePath));

    return $next($request, $response);
});
```

**Comment by chanhong** [comment]
I see but it means this have to be either in the main index.php for all routes or on each route.

Thanks for the tip.

**Comment by chanhong** [comment]
I added these code to the public\index.php but it didn't fix the Twig-View\baseUrl

$app->add(function ($request, $response, $next) {
    $uri = $request->getUri();
    echo $uri;
    $basePath = rtrim(str_ireplace('index.php', '', $uri->getBasePath()), '/');
    echo "<p />base: ".$basePath;
    $request = $request->withUri($uri->withBasePath($basePath));
    echo "<p />uri: ".$uri->withBasePath($basePath);

    return $next($request, $response);
});
// Run!
$app->run();

I might miss something.

Thanks

**Comment by akrabat** [comment]
Hmm... This is more complicated than I realised. The problem is that the Twig-View's Uri is set from the original request, not our modified one.

Will give it a bit of thought.

**Comment by akrabat** [comment]
Ping @silentworks, @codeguy for thoughts too.

**Comment by akrabat** [comment]
One question.  Is the `index.php` required to be there for routing to other pages to work? e.g. `http://example.com/index.php/news` is handled by `$app->get('/news', ...)`

**Comment by geggleto** [comment]
As far as I am concerned, if your routes are using .php files, you can fix it by manually handling such cases in the view template.

What I would recommend is simply adding another function to the TWIG template to strip out whatever you want... a replace function works perfectly for such things.

```php
{{ replace('index.php', '', base_url()) }}
```

**Comment by chanhong** [comment]
I added the line you suggested and I got the error below.

        <link href='{{ replace('index.php', '', base_url()) }}/css/style.css' rel='stylesheet' type='text/css'>

Type: Twig_Error_Syntax
Message: Unknown "replace" function in "home.twig" at line 6.

**Comment by geggleto** [comment]
Sorry @chanhong it was more a hypothetical....

I think @akrabat had the correct answer on IRC.

``` {{ base_url()|replace({'index.php':'')} }} ```

**Comment by chanhong** [comment]
Still no go.  but that would require adding this line to all template?

Type: Twig_Error_Syntax
Message: Unclosed "{" in "home.twig" at line 6.

**Comment by geggleto** [comment]
Ah yeah I had a mistake in my response.
``` {{ base_url()|replace({'index.php':'')} ```

You can read more about Twig functions and filters on their site.

**Comment by chanhong** [comment]
This work!  but it requires to put in every twig template which is not very efficient.  I think.  Thanks
{{ base_url()|replace({'index.php':''}) }}

**Comment by akrabat** [comment]
@chanhong Doing some more thinking, it would be better to remove `index.php` on construction:

```php
// Register Twig View helper
$container['view'] = function ($c) {
    $view = new \Slim\Views\Twig('path/to/templates', [
        'cache' => 'path/to/cache'
    ]);

    // Instantiate and add Slim specific extension
    $basePath = rtrim(str_ireplace('index.php', '', $c['request']->getUri()->getBasePath()), '/');
    $view->addExtension(new Slim\Views\TwigExtension($c['router'], $basePath));

    return $view;
};
```

**Comment by chanhong** [comment]
I added these lines to your skeleton\dependencies.php 
   // Instantiate and add Slim specific extension
    $basePath = rtrim(str_ireplace('index.php', '', $c['request']->getUri()->getBasePath()), '/');
    $view->addExtension(new Slim\Views\TwigExtension($c['router'], $basePath));

and the result is:
        <link href='/css/style.css' rel='stylesheet' type='text/css'>

The whole url is gone.

**Comment by chanhong** [comment]
/css/style.css

**Comment by akrabat** [comment]
I created this branch to test: https://github.com/akrabat/slim3-skeleton/tree/remove-index-php

If I go to http://slim3-skeleton.localhost/index.php/, then it works as I expect

**Comment by chanhong** [comment]
That's weird!

I had it the same but it just gave me /css/style.css instead of the full
url.

Plus what if there is a page call web.php other than index.php.

**Comment by chanhong** [comment]
The only different in my case is I use IIS and I run it from a subfolder instead of from the root

**Comment by chanhong** [comment]
when use php build in web server the page return this:
href='/css/style.css'

Same with IIS
href='/css/style.css'

**Comment by akrabat** [comment]
base_url has never include the domain name information afaik

**Comment by chanhong** [comment]
Before the fix on PHP build in server:
href='http://localhost:8888/css/style.css'

Before the fix on IIS
href='https://mysite.com/Slim3me/public/index.php/css/style.css'

So the fix didn't really fix, it just remove the whole url

**Comment by chanhong** [comment]
@akrabat 

I made these code change to dependencies.php and it works so you can ignore my pull request if you want.
   
 $url = rtrim($c->get('request')->getUri(),'/');
    // remove *.php if exist
    if (preg_match("/\.php$/i", $url)) {
        $checkurl = explode("/", $url);
        $popPHPscript = array_pop($checkurl);
        $url = implode("/", $checkurl);
    } 
    $view->addExtension(new Slim\Views\TwigExtension($c->get('router'), $url));

It would be nice if the core code return the correct url in the first place.

**Pull request closed without merging**
